package com.github.silent.samurai.speedy.metadata;

import com.github.silent.samurai.speedy.enums.ColumnType;
import com.github.silent.samurai.speedy.exceptions.NotFoundException;
import com.github.silent.samurai.speedy.interfaces.EntityMetadata;
import com.github.silent.samurai.speedy.interfaces.FieldMetadata;
import com.github.silent.samurai.speedy.interfaces.KeyFieldMetadata;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/// Exercises the backend-neutral key-provenance predicates that are the single source of truth for
/// "where does a key's value come from": {@link KeyFieldMetadata#isDatabaseGenerated()} and
/// {@link FieldMetadata#isAutoGenerated()}. The jOOQ read-back classification and the core validator
/// both consume these, so they are tested here once.
class KeyProvenanceTest {

    private static KeyFieldMetadata onlyKey(EntityMetadata md) {
        return md.getKeyFields().iterator().next();
    }

    /// IDENTITY / AUTO_INCREMENT: not insertable, not app-generated -> the database assigns it.
    @Test
    void databaseGeneratedKey() throws NotFoundException {
        EntityBuilder entity = MetadataBuilder.builder().entity("DbGen");
        entity.keyField("id", "ID", ColumnType.INTEGER).insertable(false);
        entity.field("name", "NAME", ColumnType.VARCHAR);

        KeyFieldMetadata key = onlyKey(entity.build());
        assertTrue(key.isDatabaseGenerated(), "non-insertable, non-app-generated key is DB-generated");
        assertTrue(key.isAutoGenerated(), "DB-generated keys are not required from the client");
    }

    /// Application-generated UUID: app-generated and (in JPA) not insertable. The app produces the
    /// value before insert, so it is auto-generated but NOT database-generated (no read-back).
    @Test
    void applicationGeneratedKey() throws NotFoundException {
        EntityBuilder entity = MetadataBuilder.builder().entity("AppGen");
        KeyFieldBuilder key = entity.keyField("id", "ID", ColumnType.UUID);
        key.shouldGenerateKey(true);
        key.insertable(false);
        entity.field("name", "NAME", ColumnType.VARCHAR);

        KeyFieldMetadata built = onlyKey(entity.build());
        assertFalse(built.isDatabaseGenerated(), "app-generated key must not be read back from the DB");
        assertTrue(built.isAutoGenerated(), "app-generated keys are not required from the client");
    }

    /// Client-supplied natural key: insertable, not generated -> neither auto- nor DB-generated.
    @Test
    void clientSuppliedKey() throws NotFoundException {
        EntityBuilder entity = MetadataBuilder.builder().entity("ClientKey");
        entity.keyField("id", "ID", ColumnType.INTEGER);
        entity.field("name", "NAME", ColumnType.VARCHAR);

        KeyFieldMetadata key = onlyKey(entity.build());
        assertFalse(key.isDatabaseGenerated());
        assertFalse(key.isAutoGenerated(), "a client-supplied key must be provided on create");
    }

    /// A non-key, non-insertable column (e.g. @Generated/@Formula) is auto-generated for validation
    /// purposes but is not a key, so isDatabaseGenerated does not apply to it.
    @Test
    void nonInsertableNonKeyFieldIsAutoGenerated() throws NotFoundException {
        EntityBuilder entity = MetadataBuilder.builder().entity("Computed");
        entity.keyField("id", "ID", ColumnType.UUID).shouldGenerateKey(true);
        FieldBuilder computed = entity.field("total", "TOTAL", ColumnType.INTEGER);
        computed.insertable(false);

        FieldMetadata field = entity.build().field("total");
        assertTrue(field.isAutoGenerated(), "a non-insertable column is not required from the client");
    }
}
