POST http://localhost:8080/speedy/v1/Procurement/$query
Accept: application/json
Content-Type: application/json

{
    "where": " purchaseDate < '2022-01-01T00:00:00Z' ",
    "join": {},
    "pageSize": 25,
    "pageIndex": 0,
    "orderBy": [
    ],
    "orderByDesc": [
    ]
}

###
POST http://localhost:8080/speedy/v1/$speedyQueryImpl/
Content-Type: application/json

{
    "from": "Category",
    "select": [
        "name",
        "createdBy"
    ],
    "aggregation": [
        {
            "fn": "count",
            "args": "D",
            "alias": "CNT"
        }
    ],
    "where": [
        {
            "operator": "=",
            "queryField": "NAME",
            "value": "Piyush"
        },
        {
            "operator": "in",
            "queryField": "ROLL",
            "value": [
                13
            ]
        },
        {
            "operator": "OR",
            "conditions": [
                {
                    "operator": "equal",
                    "queryField": "A",
                    "value": 5
                },
                {
                    "operator": "equal",
                    "queryField": "A",
                    "value": 10
                }
            ]
        },
        {
            "operator": "dateBetween",
            "queryField": "BIRTH",
            "value": {
                "start": "Date('')",
                "end": "Date('')"
            }
        }
    ],
    "groupBy": [
        "A",
        "B",
        "C"
    ],
    "having": [
        {
            "operator": "equal",
            "queryField": "NAME",
            "value": "Piyush"
        }
    ],
    "orderBy": [
        "A"
    ]
}

###

GET http://localhost:8080/speedy/v1/$metadata/
Accept: application/json

###

POST http://localhost:8080/speedy/v1/ValueTestEntity/$query
Accept: application/json
Content-Type: application/json

{
    "$from": "Resource",
    "$where": {
        "id": "abcd-efgh",
        "cost": {
            "$eq": "0",
            "$ne": "0",
            "$lt": "0",
            "$gt": "0",
            "$in": [
                0,
                2,
                1
            ],
            "$nin": [
                0,
                1
            ]
        },
        "$and": [
            {
                "id": "1"
            },
            {
                "desc": "desc1"
            }
        ],
        "$or": [
            {
                "id": "1"
            },
            {
                "desc": "desc1"
            }
        ]
    },
    "$orderBy": {
        "id": "ASC"
    },
    "$expand": [
        "relation"
    ],
    "$page": {
        "$index": 0,
        "$size": 100
    }
}


###


