package com.github.silent.samurai.speedy.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/// JPA entity with `@Id` and `@GeneratedValue(strategy = GenerationType.IDENTITY)`.
///
/// Used by `AutoGeneratedKeyIT` to verify that Speedy-API correctly handles
/// IDENTITY-generated primary keys (e.g., H2 `INT AUTO_INCREMENT`, MySQL
/// `AUTO_INCREMENT`, PostgreSQL `SERIAL`), including create operations where
/// the generated key is returned in the response.
@Getter
@Setter
@Table(name = "auto_gen_identity")
@Entity
public class AutoGenIdentityEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name", nullable = false)
    private String name;
}
