package com.github.silent.samurai.speedy.interfaces;


public interface KeyFieldMetadata extends FieldMetadata {


    boolean isKeyField();

    boolean shouldGenerateKey();

    /**
     * Whether the database assigns this key's value on insert (IDENTITY / AUTO_INCREMENT), as
     * opposed to the client supplying it or the application generating it
     * ({@link #shouldGenerateKey()}). DB-generated keys are not written on insert and must be
     * read back from the database afterwards. This is the strict subset of {@link #isAutoGenerated()}
     * that the database — rather than the application — produces.
     */
    default boolean isDatabaseGenerated() {
        return !isInsertable() && !shouldGenerateKey();
    }

    /**
     * A key is auto-generated when the database assigns it ({@link #isDatabaseGenerated()}) or the
     * application generates it ({@link #shouldGenerateKey()}); in either case the client need not
     * supply it on create.
     */
    @Override
    default boolean isAutoGenerated() {
        return shouldGenerateKey() || !isInsertable();
    }

}
