package com.github.silent.samurai.speedy.interfaces.metadata;

import com.github.silent.samurai.speedy.enums.ColumnType;
import com.github.silent.samurai.speedy.enums.EnumMode;
import com.github.silent.samurai.speedy.enums.EtagStrategy;
import com.github.silent.samurai.speedy.enums.ValueType;
import com.github.silent.samurai.speedy.models.DynamicEnum;
import com.github.silent.samurai.speedy.validation.rules.FieldRule;

import java.util.List;
import java.util.Optional;

public interface FieldMetadata {

    ColumnType getColumnType();

    ValueType getValueType();

    boolean isAssociation();

    boolean isCollection();

    boolean isInsertable();

    boolean isUpdatable();

    boolean isUnique();

    boolean isNullable();

    boolean isRequired();

    boolean isSerializable();

    boolean isDeserializable();

    String getDbColumnName();

    String getOutputPropertyName();

    EntityMetadata getEntityMetadata();

    EntityMetadata getAssociationMetadata();

    /// The target key field this association's *first* foreign-key column references. Convenience
    /// accessor for the common single-column case; {@link #getAssociationColumns()} is the complete
    /// mapping and is what callers that touch columns must use.
    FieldMetadata getAssociatedFieldMetadata();

    /// The (local column -> target key field) pairs this association is mapped through, ordered by
    /// the target entity's key-field order. Empty for a non-association field, a single element for
    /// a single-column foreign key, and one element per key column when the target has a composite
    /// primary key (JPA's {@code @JoinColumns}).
    ///
    /// The default derives the single-column mapping from {@link #getDbColumnName()} and
    /// {@link #getAssociatedFieldMetadata()}, so an implementation that only supports single-column
    /// foreign keys needs no change.
    default List<AssociationColumn> getAssociationColumns() {
        if (!isAssociation()) {
            return List.of();
        }
        return List.of(new AssociationColumn(getDbColumnName(), getAssociatedFieldMetadata()));
    }

    /// Whether this association is mapped through more than one foreign-key column — i.e. its target
    /// has a composite primary key.
    default boolean isCompositeAssociation() {
        return getAssociationColumns().size() > 1;
    }

    // Enum metadata
    boolean isEnum();

    // New: explicit accessors for stored vs operational enum config
    EnumMode getStoredEnumMode();

    EnumMode getOperationalEnumMode();

    DynamicEnum getDynamicEnum();

    /**
     * Whether this field is marked sensitive via {@code @SpeedySensitive}.
     * Sensitive fields are blocked from appearing on the right-hand side
     * of {@code $} field references in query conditions.
     */
    boolean isSensitive();

    /**
     * Whether this field's value is supplied by something other than the client — a
     * non-insertable column whose value comes from the database (an IDENTITY/AUTO_INCREMENT key,
     * or a computed/generated column such as {@code @Generated}/{@code @Formula}). Such fields are
     * not required in a create payload. {@link KeyFieldMetadata} widens this to also cover
     * application-generated keys ({@link KeyFieldMetadata#shouldGenerateKey()}).
     */
    default boolean isAutoGenerated() {
        return !isInsertable();
    }

    /**
     * List of generic validation specs derived from field annotations.
     * Implementations may override; default is empty list.
     */
    default List<FieldRule> getValidations() {
        return List.of();
    }

    /**
     * How Speedy refreshes this field as the entity's conditional-request token, declared via
     * {@code @SpeedyETag} (or an auto-honored JPA {@code @Version} of a compatible type).
     * Speedy stamps a fresh value into this field on every create/update/replace and reads it
     * back to form the {@code ETag}; the client can never set it ({@link #isDeserializable()}
     * is false). Returns empty for every field that did not opt in — callers on the
     * conditional-request path must short-circuit on this being empty.
     */
    default Optional<EtagStrategy> getEtagStrategy() {
        return Optional.empty();
    }

}
