package com.github.silent.samurai.speedy.entity;

import com.github.silent.samurai.speedy.TestApplication;
import com.github.silent.samurai.speedy.client.test.SpeedyTest;
import com.github.silent.samurai.speedy.client.test.SpeedyTestResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

/// Tests CRUD operations on entities with non-UUID generated primary keys.
///
/// ## What we test
/// Speedy's PK handling for `@GeneratedValue(strategy = GenerationType.IDENTITY)`
/// and `GenerationType.AUTO` — CREATE without specifying an ID should auto-generate
/// the PK, and the full CRUD lifecycle (get/update/delete) should work with that
/// generated key. This covers the "non-UUID generated value" path in the metamodel
/// processor and PK query builders.
///
/// ## How we test
/// Integration tests via MockMvc that call the Speedy API endpoints.
/// AutoGenIdentityEntity uses @GeneratedValue(strategy=IDENTITY) on `Long id`.
/// AutoGenAutoEntity uses @GeneratedValue(strategy=AUTO) on `Long id`.
/// We CREATE without providing an id, verify the response includes a generated id,
/// then use that id for subsequent GET/UPDATE/DELETE operations.
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK, classes = TestApplication.class)
@AutoConfigureMockMvc(addFilters = false)
class AutoGeneratedKeyTest {

    @Autowired
    MockMvc mockMvc;

    private SpeedyTest client;

    @BeforeEach
    void setUp() {
        client = SpeedyTest.mockMvc(mockMvc);
    }

    @Nested
    @DisplayName("IDENTITY generation")
    class IdentityGeneration {

        @Test
        @DisplayName("CREATE without ID should auto-generate via IDENTITY")
        void createAutoGenIdentityWithoutId() {
            client.create("AutoGenIdentityEntity")
                    .field("name", "identity-test-1")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");
        }

        @Test
        @DisplayName("CREATE, query, update, delete lifecycle with IDENTITY PK")
        void identityLifecycle() {
            SpeedyTestResult createResult = client.create("AutoGenIdentityEntity")
                    .field("name", "identity-lifecycle")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");

            String id = String.valueOf(createResult.jsonPath("$.payload[0].id", Object.class));

            client.get("AutoGenIdentityEntity")
                    .key("id", id)
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].name");

            client.update("AutoGenIdentityEntity")
                    .key("id", id)
                    .field("name", "identity-updated")
                    .execute()
                    .expectOk();

            client.delete("AutoGenIdentityEntity")
                    .key("id", id)
                    .execute()
                    .expectOk();
        }
    }

    @Nested
    @DisplayName("AUTO generation")
    class AutoGeneration {

        @Test
        @DisplayName("CREATE without ID should auto-generate via AUTO")
        void createAutoGenAutoWithoutId() {
            client.create("AutoGenAutoEntity")
                    .field("name", "auto-test-1")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");
        }

        @Test
        @DisplayName("CREATE, query, update, delete lifecycle with AUTO PK")
        void autoLifecycle() {
            SpeedyTestResult createResult = client.create("AutoGenAutoEntity")
                    .field("name", "auto-lifecycle")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");

            String id = String.valueOf(createResult.jsonPath("$.payload[0].id", Object.class));

            client.get("AutoGenAutoEntity")
                    .key("id", id)
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].name");

            client.update("AutoGenAutoEntity")
                    .key("id", id)
                    .field("name", "auto-updated")
                    .execute()
                    .expectOk();

            client.delete("AutoGenAutoEntity")
                    .key("id", id)
                    .execute()
                    .expectOk();
        }

        @Test
        @DisplayName("Multiple CREATE with AUTO generation")
        void multipleCreateAuto() {
            SpeedyTestResult result1 = client.create("AutoGenAutoEntity")
                    .field("name", "multi-auto-1")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");

            SpeedyTestResult result2 = client.create("AutoGenAutoEntity")
                    .field("name", "multi-auto-2")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");

            SpeedyTestResult result3 = client.create("AutoGenAutoEntity")
                    .field("name", "multi-auto-3")
                    .execute()
                    .expectOk()
                    .expectJsonPathExists("$.payload[0].id");
        }
    }
}
