name: Publish package to the Maven Central Repository
on:
    push:
        branches:
            - release-spring-3

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Maven Central Repository
                uses: actions/setup-java@v1
                with:
                    java-version: 17
                    server-id: ossrh
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD
                    gpg-passphrase: MAVEN_GPG_PASSPHRASE
            -   id: install-secret-key
                name: Install gpg secret key
                run: |
                    cat <(echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --batch --import
                    gpg --list-secret-keys --keyid-format LONG
            -   id: publish-to-central
                name: Publish to Central Repository
                env:
                    MAVEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
                run: |
                    mvn --no-transfer-progress --batch-mode clean deploy -P=ossrh
